#drop database if exists P1spot;

CREATE Database P1spot;

USE P1spot;

### Table

CREATE Table Config (
	`Key` varchar(32),
	`Value` varchar(200),
	PRIMARY KEY (`Key`)
);

INSERT INTO Config VALUES('SchemaVersion','2');

### Table 

CREATE TABLE `P1device` (
	`Head` VARCHAR(32) NOT NULL,
	`TimeStamp` INT(4) NOT NULL DEFAULT '0',
	`TimeStampmysql` TIMESTAMP NULL DEFAULT NULL,
	`Serial` VARCHAR(34) NOT NULL,
	`Name` VARCHAR(32) NULL DEFAULT NULL,
	`Type` VARCHAR(32) NULL DEFAULT NULL,
	`SW_Version` VARCHAR(4) NULL DEFAULT NULL,
	`Energyimport` INT(10) NULL DEFAULT '0',
	`EnergyimportPeakOff` INT(10) UNSIGNED NULL DEFAULT '0',
	`EnergyimportPeak` INT(10) UNSIGNED NULL DEFAULT '0',
	`Energyexport` INT(10) NULL DEFAULT '0',
	`EnergyexportPeakOff` INT(10) UNSIGNED NULL DEFAULT '0',
	`EnergyexportPeak` INT(10) UNSIGNED NULL DEFAULT '0',
	`Tariff` INT(1) NULL DEFAULT NULL,
	`Pimport` SMALLINT(5) NULL DEFAULT '0',
	`Pexport` SMALLINT(5) NULL DEFAULT '0',
	`Failureany` INT(4) NULL DEFAULT NULL,
	`Failurelong` INT(4) NULL DEFAULT NULL,
	`Failuretimes` INT(4) NULL DEFAULT NULL,
	`Failurelog` VARCHAR(50) NULL DEFAULT NULL,
	`Failevent` INT(4) NULL DEFAULT NULL,
	`Failevent1` VARCHAR(10) NULL DEFAULT NULL,
	`Failevent2` VARCHAR(10) NULL DEFAULT NULL,
	`Faileventcode` VARCHAR(20) NULL DEFAULT NULL,
	`Faileventduration` INT(4) NULL DEFAULT NULL,
	`Usag` INT(4) NULL DEFAULT NULL,
	`Usag1` INT(4) NULL DEFAULT NULL,
	`Usag2` INT(4) NULL DEFAULT NULL,
	`Usag3` INT(4) NULL DEFAULT NULL,
	`Uswell` INT(4) NULL DEFAULT NULL,
	`Uswell1` INT(4) NULL DEFAULT NULL,
	`Uswell2` INT(4) NULL DEFAULT NULL,
	`Uswell3` INT(4) NULL DEFAULT NULL,
	`Iac` INT(1) NULL DEFAULT NULL,
	`Iac1` INT(1) NULL DEFAULT NULL,
	`Iac2` INT(1) NULL DEFAULT NULL,
	`Iac3` INT(1) NULL DEFAULT NULL,
	`PacI` SMALLINT(6) NULL DEFAULT '0',
	`PacI1` SMALLINT(6) NULL DEFAULT '0',
	`PacI2` SMALLINT(6) NULL DEFAULT '0',
	`PacI3` SMALLINT(6) NULL DEFAULT '0',
	`PacE` SMALLINT(6) NULL DEFAULT '0',
	`PacE1` SMALLINT(6) NULL DEFAULT '0',
	`PacE2` SMALLINT(6) NULL DEFAULT '0',
	`PacE3` SMALLINT(6) NULL DEFAULT '0',
	`Gasm3DeviceType` INT(1) NULL DEFAULT NULL,
	`Gasm3Serial` VARCHAR(34) NOT NULL,
	`Gasm3timestamp` INT(4) NULL DEFAULT NULL,
	`Gasm3timestampmysql` TIMESTAMP NULL DEFAULT NULL,
	`Gasm3` FLOAT UNSIGNED NULL DEFAULT NULL,
	`Message` VARCHAR(50) NULL DEFAULT NULL,
	`Unknown` VARCHAR(50) NULL DEFAULT NULL,
	`Tail` VARCHAR(8) NULL DEFAULT NULL,
	`Status` VARCHAR(10) NULL DEFAULT NULL,
	`Temperature` FLOAT NULL DEFAULT NULL,
	`EnergyimportDelta` INT(10) NULL DEFAULT '0',
	`EnergyimportPeakOffDelta` INT(10) UNSIGNED NULL DEFAULT '0',
	`EnergyimportPeakDelta` INT(10) UNSIGNED NULL DEFAULT '0',
	`EnergyexportDelta` INT(10) NULL DEFAULT '0',
	`EnergyexportPeakOffDelta` INT(10) UNSIGNED NULL DEFAULT '0',
	`EnergyexportPeakDelta` INT(10) UNSIGNED NULL DEFAULT '0',
	`EnergyimportDaily` INT(10) UNSIGNED NULL DEFAULT '0'
	`EnergyexportDaily` INT(10) UNSIGNED NULL DEFAULT '0'
	PRIMARY KEY (`TimeStamp`)
);


